name: Download ParaTranz translations
on:
  workflow_call:
  workflow_dispatch:

permissions: write-all

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
      - name: Setup Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.11
      - uses: actions/cache@v4.0.2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: Download translated
        env:
          PARATRANZ_TOKEN: ${{ secrets.PARATRANZ_TOKEN }}
        run: |
          python .github/scripts/download_translated.py
      - name: Commit translated file from ParaTranz
        uses: EndBug/add-and-commit@v9
        with:
          add: translated
          message: New translated file from ParaTranz
      - uses: actions/upload-artifact@v4
        with:
          name: "Translate for Dimension Hopper:The Fall"
          path: translated/
      - uses: actions/upload-artifact@v4
        with:
          name: paratranz
          path: artifacts.zip
  release:
    runs-on: ubuntu-latest
    needs:
      - download
    steps:
      - uses: actions/download-artifact@v4
        name: "Translate for Dimension Hopper:The Fall"

      - name: Zip
        run: |
          zip -r "Translate for Dimension Hopper:The Fall.zip" chinese-build.${{ github.run_number }}

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          title: Translate for Dimension Hopper:The Fall-pre7
          automatic_release_tag: build.${{ github.run_number }}
          files: |
            Translate for Dimension Hopper:The Fall.zip
